/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExpoRouteImport } from './routes/expo'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollegesRouteImport } from './routes/colleges'
import { Route as AptitudeRouteImport } from './routes/aptitude'
import { Route as IndexRouteImport } from './routes/index'

const ExpoRoute = ExpoRouteImport.update({
  id: '/expo',
  path: '/expo',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesRoute = CollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => rootRouteImport,
} as any)
const AptitudeRoute = AptitudeRouteImport.update({
  id: '/aptitude',
  path: '/aptitude',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aptitude': typeof AptitudeRoute
  '/colleges': typeof CollegesRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/expo': typeof ExpoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aptitude': typeof AptitudeRoute
  '/colleges': typeof CollegesRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/expo': typeof ExpoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aptitude': typeof AptitudeRoute
  '/colleges': typeof CollegesRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/expo': typeof ExpoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aptitude' | '/colleges' | '/contact' | '/courses' | '/expo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aptitude' | '/colleges' | '/contact' | '/courses' | '/expo'
  id:
    | '__root__'
    | '/'
    | '/aptitude'
    | '/colleges'
    | '/contact'
    | '/courses'
    | '/expo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AptitudeRoute: typeof AptitudeRoute
  CollegesRoute: typeof CollegesRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  ExpoRoute: typeof ExpoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/expo': {
      id: '/expo'
      path: '/expo'
      fullPath: '/expo'
      preLoaderRoute: typeof ExpoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges': {
      id: '/colleges'
      path: '/colleges'
      fullPath: '/colleges'
      preLoaderRoute: typeof CollegesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aptitude': {
      id: '/aptitude'
      path: '/aptitude'
      fullPath: '/aptitude'
      preLoaderRoute: typeof AptitudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AptitudeRoute: AptitudeRoute,
  CollegesRoute: CollegesRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  ExpoRoute: ExpoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
